ProjectMultiShop/ProjectMultiShop/Models/Category.cs
namespace ProjectMultiShop.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImgPath { get; set; }
    }
}

ProjectMultiShop/ProjectMultiShop/Models/Contact.cs
namespace ProjectMultiShop.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMultiShop.Context;
using ProjectMultiShop.Models;

namespace ProjectMultiShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {

        private readonly AppDbContext _context;

        public CategoryController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            List<Category> categories = _context.Categories.ToList();
            return View(categories);
        }

        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]

        public IActionResult Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }

            _context.Categories.Add(category);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Update(int Id)
        {
            return View();
        }

        [HttpPost]
        public IActionResult Update(int Id, Category category)
        {
            Category newcategory = _context.Categories.Find(category.Id);
            newcategory.Name = category.Name;
            newcategory.ImgPath = category.ImgPath;
            _context.Categories.Update(newcategory);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


    }
}

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMultiShop.Context;
using ProjectMultiShop.Models;

namespace ProjectMultiShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactController : Controller
    {
        private readonly AppDbContext _context;

        public ContactController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Contact> contacts = _context.Contacts.ToList();
            return View(contacts);
        }

        
        public IActionResult Delete(int Id)
        {
            Contact contact = _context.Contacts.Find(Id);
            _context.Contacts.Remove(contact);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

    }
}

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectMultiShop.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjectMultiShop/ProjectMultiShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectMultiShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ProjectMultiShop/ProjectMultiShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ProjectMultiShop.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }
}

ProjectMultiShop/ProjectMultiShop/Controllers/ShopController.cs
using Microsoft.AspNetCore.Mvc;

namespace ProjectMultiShop.Controllers
{
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShopDetail()
        {
            return View();
        }
    }
}

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Views/Category/Create.cshtml
@model Category
@{
    ViewData["Title"] = "Create";
}

<div class="card-body">
    <h4 class="card-title">Create Category</h4>
    <form class="forms-sample">
        <div>  </div>
        <div class="form-group"
             <div>


                  <input type="text" class="form-control" id="exampleInputUsername1" placeholder="Category Name">
             </div>
        </div>
        <button type="submit" class="btn btn-primary me-2">Add</button>
        <button class="btn btn-dark">Cancel</button>
    </form>
</div>

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Views/Category/Index.cshtml
@model List<Category>
@{
    ViewData["Title"] = "Category";
}

<div class="row">

    <div class="col-lg-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Hoverable Table</h4>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <div class="d-flex justify-content-end"> <a type="button" asp-area="Admin" asp-controller="Category" asp-action="Create" class="btn btn-outline-success btn-sm">Create</a></div>
                            <tr>
                                <th>Category ID</th>
                                <th>Category Name</th>
                                <th>ImagePath</th>
                                <th>CRUD</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Category category in Model)
                            {
                                <tr>
                                    
                                    <td>@category.Id</td>
                                    <td>@category.Name</td>
                                    <td>@category.ImgPath</td>
                                    <td>
                                        <a type="button" asp-area="Admin" asp-controller="Category" asp-action="Update" class="btn btn-outline-info btn-sm">Update</a>
                                        <button type="button" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Views/Category/Update.cshtml
@model Category
@{
    ViewData["Title"] = "Update";
}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create category</h4>
            <form class="forms-sample" action="Update" method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <label asp-for="ImgPath"></label>
                    <input asp-for="ImgPath" class="form-control" placeholder="Image Path">
                </div>
                <button type="submit" class="btn btn-outline-info btn-sm">Submit changes</button>
                <a type="button" class="btn btn-outline-danger btn-sm" asp-controller="Dashboard" asp-action="Index">Cancel</a>
            </form>
        </div>
    </div>
</div>

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Views/Contact/Index.cshtml
@model List<Contact>
@{
    ViewData["Title"] = "Index";
}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Customer messages</h4>
            <div class="table-responsive">
                <table class="table table-bordered text-center">
                    <thead>
                        <tr>
                            <th> Id </th>
                            <th> Name </th>
                            <th> E-mail </th>
                            <th> Subject </th>
                            <th> Message </th>
                            <th>Operation</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Contact contact in Model)
                        {
                            <tr>
                                <td> @contact.Id</td>
                                <td> @contact.Name </td>
                                <td>
                                    @contact.Email
                                </td>
                                <td> @contact.Subject </td>
                                <td> @contact.Message </td>
                                <td><a asp-controller="Contact" asp-action="Delete" asp-route-Id="@contact.Id" type="button" class="btn btn-outline-danger btn-sm">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

ProjectMultiShop/ProjectMultiShop/Areas/Admin/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Admin Panel";
}

<h1>Dashboard</h1>

ProjectMultiShop/ProjectMultiShop/Views/Contact/Index.cshtml
@model Contact
@{
    ViewData["Title"] = "Index";
}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <span class="breadcrumb-item active">Contact</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Contact Start -->
<div class="container-fluid">
    <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Contact Us</span></h2>
    <div class="row px-xl-5">
        <div class="col-lg-7 mb-5">
            <div class="contact-form bg-light p-30">
                <div id="success"></div>
                <form method="post">
                    <div class="control-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" type="text" class="form-control" placeholder="Your Name" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" type="email" class="form-control" placeholder="Your Email" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <label asp-for="Subject"></label>
                        <input asp-for="Subject" type="text" class="form-control" placeholder="Subject" />
                        <p class="help-block text-danger"></p>
                    </div>
                    <div class="control-group">
                        <label asp-for="Message"></label>
                        <textarea asp-for="Message" class="form-control" rows="8" placeholder="Message"></textarea>
                        <p class="help-block text-danger"></p>
                    </div>
                    <div>
                        <button class="btn btn-primary py-2 px-4" type="submit">
                            Send
                            Message
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-lg-5 mb-5">
            <div class="bg-light p-30 mb-30">
                <iframe style="width: 100%; height: 250px;"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
            </div>
            <div class="bg-light p-30 mb-3">
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>123 Street, New York, USA</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>info@example.com</p>
                <p class="mb-2"><i class="fa fa-phone-alt text-primary mr-3"></i>+012 345 67890</p>
            </div>
        </div>
    </div>
</div>
<!-- Contact End -->